name: Flutter Build

concurrency:
  group: flutter-build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Windows build
        run: flutter build windows

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Installer
        env:
          VERSION: 1.0.${{ github.run_number }}
        run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" Setup.iss'

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: v1.0.${{ github.run_number }}
          files: adb-wrapper-setup-1.0.${{ github.run_number }}.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
