name: Flutter Build

concurrency:
  group: flutter-build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set version in pubspec.yaml
        run: |
          $version = "1.0.${{ github.run_number }}"
          (Get-Content pubspec.yaml) -replace '^version:.*', "version: $version" | Set-Content pubspec.yaml
        shell: pwsh

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Windows build
        run: flutter build windows

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Installer
        env:
          VERSION: 1.0.${{ github.run_number }}
        run: '& "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" Setup.iss'

      - name: Generate changelog
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 || echo "")
          if [ -z "$PREV_TAG" ]; then
            echo "No previous tag found"
            echo "changelog=* Initial release" >> $GITHUB_OUTPUT
          else
            echo "Generating changelog since $PREV_TAG"
            LOG=$(git log $PREV_TAG..HEAD --pretty=format:"- %s (%h)")
            echo "changelog<<EOF" >> $GITHUB_OUTPUT
            echo "$LOG" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: v1.0.${{ github.run_number }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: adb-wrapper-setup-1.0.${{ github.run_number }}.exe
          #generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
